include:
  - project: "fif/dx/configurable-pipelines/nx-build-pipeline"
    ref: v5
    file: "pipeline.yml"

variables:
  PROJECT_NAME: gateway-compras-frontend
  SERVICE_NAME: $PROJECT_NAME-$APP_NAME
  ROLE_ID: $BANCO_CO_CROSS_PREPROD_GATEWAY_COMPRAS_BACKEND_TEST_VAULT_ROLE_ID
  SECRET_ID: $BANCO_CO_CROSS_PREPROD_GATEWAY_COMPRAS_BACKEND_TEST_VAULT_SECRET_ID
  CLUSTER_NAME: banco-co-cross-preprod-cluster
  INSTALL_DEPS_SCRIPT: "npm install"
  IMAGE_NAME: hub.fif.tech/gateway-compras-backend/$PROJECT_NAME-ui
  RUN_LINTER: "false"
  DEPLOY_PLATFORM: "argocd"
  DOCKER_EXTRA_BUILD_ARGS_ENV: "--build-arg=BUILDCOMMAND='npx nx run $APP_NAME:build' --build-arg=BUILDPATH='dist/apps/$APP_NAME'"

  DOCKER_FILE_PATH: $CI_PROJECT_DIR/apps/$APP_NAME/Dockerfile

image: hub.fif.tech/base/node-dev:20-wolfi-latest