include:
  - project: 'tech-corp/seguridad-de-la-informacion/ci-templates/dependency-check'
    ref: v8.2.1-v9.0.7
    file: '/template/.ci-template.yml'
  - project: 'fif/dx/gitlab-templates/security/sonarqube'
    ref: v2
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/versioning/gitlab-tagging-template'
    ref: v1
    file: 'template.yml'
  - project: 'fif/canales-digitales/fif-tools/ci-templates/building/docker-build-tag-template'
    ref: v1
    file: 'template.yml'
  - project: 'fif/canales-digitales/fif-tools/ci-templates/building/update-service-k8s-deploy-template'
    ref: v1
    file: 'template.yml'
  - project: 'fif/canales-digitales/fif-tools/ci-templates/building/helm-push-template'
    ref: v2
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/versioning/validate-version'
    ref: v1
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/testing/eslint'
    ref: v1
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/testing/coverage-test'
    ref: v1
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/testing/nodejs-scan'
    ref: v1
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/installing/install-dependencies'
    ref: v1
    file: 'template.yml'
  - project: 'fif/dx/gitlab-templates/security/trivy'
    ref: v1
    file: 'template.yml'
  - project: 'fif/canales-digitales/fif-tools/ci-templates/building/upload-static-template'
    ref: v1.1.3
    file: 'template.yml'
default:
  tags:
    - ${DEFAULT_GROUP_CI_RUNNER_TAG}

variables:
  PROJECT_NAME: gateway-compras-backend

  DOCKER_FILE_PATH: $CI_PROJECT_DIR/Dockerfile
  SERVICE_NAME: gateway-compras-frontend
  IMAGE_NAME: hub.fif.tech/gateway-compras-backend/ui/$PROJECT_NAME

  CLUSTER_NAME: banco-co-cross-preprod-cluster
  SECRET_ID: $BANCO_CO_CROSS_PREPROD_GATEWAY_COMPRAS_BACKEND_TEST_VAULT_SECRET_ID
  ROLE_ID: $BANCO_CO_CROSS_PREPROD_GATEWAY_COMPRAS_BACKEND_TEST_VAULT_ROLE_ID

  HELM_CHART_REPO: https://hub.fif.tech/chartrepo/gateway-compras-backend
  HELM_CHART_REPO_NAME: gateway-compras-backend
  HELM_CHART_PATH: "charts/$SERVICE_NAME/."

  TP_BRANCH: master
  TP_NPM_ESLINT_SCRIPT: not-implemented
  TP_NPM_COVERAGE_SCRIPT: not-implemented
  TP_NPM_MUTATION_SCRIPT: not-implemented

  UPDSRV_PROJECT_URL: https://gitlab.falabella.tech/fif/canales-digitales/fanatizar-clientes/bfco/gateway-compras/gateway-compras-frontend-deploy
  UPDSRV_PRODUCT_NAME: $SERVICE_NAME
  UPDSRV_SERVICE_NAME: $SERVICE_NAME
  UPDSRV_PROJECT_BRANCH: main
  # TAG: {tag}

before_script:
  - export TAG=$(head -n 1 tag)

image: hub.fif.tech/base/node-dev:18-latest

cache:
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - node_modules/
    - upload-tmp
    - tag

stages:
  - validate-version
  - install
  - test
  - compile
  - build
  - image-test
  - git-tag
  - prepare-files
  - upload
  - update-deploy

validate-version:
  stage: validate-version
  extends: .validate-version-to-build
  before_script:
    - |
      export TAG=$(jq '.version' -r package.json)
      echo $TAG > tag
      cat tag
  rules:
    - if: $CI_COMMIT_BRANCH == $TP_BRANCH

install-dependencies:
  extends: .install-dependencies
  except:
    - tags

eslint:
  extends: .eslint
  except:
    - tags

nodejs-scan:
  extends: .nodejs-scan
  except:
    - tags

dependency-check-analysis:
  extends: .dependency-cli-8
  stage: test
  allow_failure: true
  image: hub.fif.tech/base/plugins/dependency-check:9
  variables:
    PROJECT_NAME: $PROJECT_NAME-ui
    DC_TARGET_LANG: node
  tags:
    - fif-runner
  except:
    - tags

compile:
  stage: compile
  script:
    - npm prune --production
  rules:
    - if: $CI_COMMIT_BRANCH == $TP_BRANCH

build:
  stage: build
  extends: .buildah-build
  before_script:
    - export TAG=$(head -n 1 tag)
    - if [ "$HARBOR_PROJECT_NAME" != "" ]; then
    -   export PROJECT_NAME=$HARBOR_PROJECT_NAME
    - fi
  variables:
    CI_REGISTRY: hub.fif.tech
    CI_REGISTRY_SIMPLE_SIGN_IN: "yes"
    CI_REGISTRY_USER: $DOCKER_USER
    CI_REGISTRY_PASSWORD: $DOCKER_PASSWORD
  rules:
    - if: $CI_COMMIT_BRANCH == $TP_BRANCH

git-tag:
  extends: .git-tag
  stage: git-tag
  before_script:
    - export TAG=v$(head -n 1 tag)
  rules:
    - if: $CI_COMMIT_BRANCH == $TP_BRANCH

helm-push:
  stage: build
  extends: .helm-push
  rules:
    - if: $CI_COMMIT_BRANCH == $TP_BRANCH

update-service-project:
  extends: .update-deploy
  stage: update-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $TP_BRANCH && $UPDSRV_DISABLED != "YES"

prepare-files:
  stage: prepare-files
  image: hub.fif.tech/base/node-dev:18-latest
  script:
    - npm install
    - npm run build
    # - sh .prepare-file-css-upload.sh
  tags:
    - fif-runner
  only:
    - main

# upload-cdn:
#   extends: .upload-static
#   stage: upload
#   variables:
#     ROLE_ID: $FIF_STATIC_QA_VAULT_ROLE_ID
#     SECRET_ID: $FIF_STATIC_QA_VAULT_SECRET_ID
#     STATIC_SLUG: fif-static
#     ENV_SLUG: qa
#     STORAGE_ACCOUNT_NAME: fifstaticqa
#     CONTAINER: insurance-assets
#     UPLOAD_FOLDER: upload-tmp
#     ACTION: upload
#     TTL: 300
#   tags:
#     - fif-runner
#   only:
#     - master
#   when: manual

# upload-prod:
#   extends: .upload-static
#   stage: upload
#   variables:
#     ROLE_ID: $FIF_STATIC_PROD_VAULT_ROLE_ID
#     SECRET_ID: $FIF_STATIC_PROD_VAULT_SECRET_ID
#     STATIC_SLUG: fif-static
#     ENV_SLUG: prod
#     STORAGE_ACCOUNT_NAME: fifstaticprod
#     CONTAINER: insurance-assets
#     UPLOAD_FOLDER: upload-tmp
#     ACTION: upload
#     TTL: 300
#   tags:
#     - fif-runner
#   only:
#     - master
#   when: manual
