name: gateway-compras-frontend
labels:
  app: gateway-compras-frontend
  lang: node
  platform: services
selectorLabels:
  app: gateway-compras-frontend
# The following lines correspond to the definition of our kubernetes objects.
# We define the features of our deployment
deployment:
  revisionHistoryLimit: 1 # is for avoid the creation of a lot of replicasets. increase the number if you keep previous replicasets as backups.
  annotations: #These annotations must be mandatory, since they are necessary to be able to connect our services with vault.
    vault.security.banzaicloud.io/vault-addr: "https://vault.fif.tech:8200"
    vault.security.banzaicloud.io/vault-role: "gateway-compras-backend-test"
    vault.security.banzaicloud.io/vault-path: "banco-co-cross-preprod"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  image:
    repository: hub.fif.tech/gateway-compras-backend/ui/gateway-compras-frontend
    version: '0.0.1'
    pullPolicy: Always
  replicaCount: 1
  port: 3000
  imagePullSecrets: #This attribute must be mandatory, since they are the credentials to be able to download the images from the harbor.
    - name: harbor-reg-cred
  serviceAccountName: vault-auth-fif # required attribute to allow the vault access
  # the below field is the strategy to use on our deployment or argo rollout
  # this is a example of how to configure a canary deploy
  # you can keep it commented or delete it to use the default behabior that is a blue-green deploy
  # for more documentation, check our wiki page at: https://gitlab.falabella.tech/fif/canales-digitales/devops/devops-experience/cross/awesome-k8s/-/wikis/deployments
  # strategy:
  #   canary:
  #     steps:
  #       - setWeight: 20
  #        The following pause step will pause the rollout indefinitely until manually resumed.
  #       Rollouts can be manually resumed by running `kubectl argo rollouts promote ROLLOUT`
  #       - pause: {}
  #       - setWeight: 40
  #       - pause: {duration: 40s}
  #       - setWeig-´´ht: 60
  #       - pause: {duration: 20s}
  #       - setWeight: 80
  #       - pause: {duration: 20s}
  # The variables that will be loaded into our pod are listed below.
  # replace the examples and add many that you need
  env:
    APP_ENV: qa
  # check our documentation of probes: https://gitlab.falabella.tech/fif/canales-digitales/devops/devops-experience/cross/awesome-k8s/-/wikis/startup-readiness-livenes-probes
  # the liveness probe thats check healty of the container.
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
  # the readiness probes that checks that the container can handle new requests
  # readinessProbe:
  #   httpGet:
  #     path: /ready
  #     port: 8005
  #   initialDelaySeconds: 5
  #   periodSeconds: 3
  # the startup probe that checks  that the container started correctly
  startupProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5 # the number of failed atempts that the probe use to determine that the startup process failed
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
hpa:
  enabled: true # This boolean tells us if the hpa will be abailable in deployment.
  # below is a example how to define hpa, if you need them
  # onlycpu:
  #   targetCPUUtilizationPercentage: 80
  maxReplicas: 3
  cpu:
    averageUtilization: 80
  memory:
    targetAverageValue: 80
    # requests:
    #   targetAverageValue: 80
# We define the features of our service
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
# We define the features of our virtualService
virtualService:
  create: false # This boolean tells us if the virtualService will be created in our cluster.
  # below is a example how to define virtual services if you need them
  # host: "seguros-automotriz-test.fif.tech"
  # customHTTP: true
  # http:
  #     - match:
  #    uri_prefix: /your/public/path
  #    uri_rewrite: /your/internal/path
  # destination:
  #  port: 80
# We define the features of our ingress
ingress:
  enabled: false # This boolean tells us if the ingress will be created in our cluster.
# We define the features of our serviceAccount
serviceAccount:
  create: false # This boolean tells us if the serviceAccount will be created in our cluster.
# We define the features of our jwt security definition. This configuration create authorizationPolicy and requestAuthentication resources
# more information at: https://gitlab.falabella.tech/fif/canales-digitales/devops/devops-experience/cross/awesome-k8s/-/wikis/jwt-security
jwtSecurity:
  create: false # This boolean tells us if the jwt security resources (authorizationPolicy and requestAuthentication) will be created in our cluster.
  labels: #optional
    foo: bar
  annotations: #optional
    foo: bar
  matchLabels:
    privategroup: bar
  principals:
    - issuer: jwt-iss # this to be match a namespace
      subject: seguros-automotriz-test # this to be match a namespace
destinationRule:
  create: false # set it to true if you want to create a destination rule for use in trafic routing on a canary deploy
  # next is the rules section, to define custom rules for our destinationRule
  # if you want, you can delete it to use the default canary and stable rules
  rules:
    - name: stable
      labels:
        app: gateway-compras-frontend
    - name: canary
      labels:
        app: gateway-compras-frontend
