version: '3.1'
services:
    front:
      image: hub.fif.tech/$CLUSTER/$IMAGE_NAME:$ENVIRONMENT
      restart: always
      environment:
        - SERVICE=1
        - NAME_ENV = ${NAME_ENV}
      deploy:
          replicas: ${REPLICAS}
          update_config:
            delay: 30s
            parallelism: 1
      ports:
        - ${PORT_SERVICE}
      volumes:
        - "/logs-pool:/var/log/pm2"
      logging:
        driver: json-file
        options:
          max-size: 10m
          max-file: 10